apiVersion: v1
kind: Service
metadata:
  labels:
    app: reversewords-dev-app
  name: reverse-words
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: reversewords-dev-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reversewords-dev-app
  name: reverse-words
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reversewords-dev-app
  template:
    metadata:
      labels:
        app: reversewords-dev-app
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release v0.0.3
        image: quay.io/mavazque/reversewords:v0.0.3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 2
        name: reverse-words
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 2
