apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: reversewords-pro-app-subscription
  namespace: reverse-words-prod
  labels:
    app: reversewords-pro-app
  annotations:
    apps.open-cluster-management.io/github-path: apps/reversewords/
    apps.open-cluster-management.io/github-branch: prod
spec:
  channel: open-cluster-management/acm-app-lifecycle-blog
  placement:
    placementRef:
      kind: PlacementRule
      name: production-clusters

